### PR TITLE
Add Timer Labeler Program

### PR DESCRIPTION
**Pull request by dfashbaugh**
This PR contains a simple cute interface for timing and labeling videos. The output is a CSV file that can be loaded into other software. 

This also organizes the original bus view program into its own subfolder.

### CODE REVIEW

**Comment by KacobJeith** [comment]
Do you have a quick description of how to run it? Maybe a screenshot of the UI for quick reference?

**Comment by KacobJeith** [comment]
Could we put this in a folder without spaces? I just find it so annoying to escape spaces when crawling through folders in terminals and stuff

**Comment by KacobJeith** [comment]
Yeah I'm struggling to install all the right .NET versions and frameworks to run this, could you add a quick README with dependency requirements to run?

**Comment by dfashbaugh** [comment]
I'm not really sure what you're trying to do, but you should be able to just open this using Unity and run it on a Mac. The build I zipped is for Windows though, so if you're trying to run that build, you're not going to get anywhere on Mac.

Also, why do spaces bother you? You can just autocomplete them.

**Comment by dfashbaugh** [comment]
Let me know if it doesn't work though. there should be no dependencies outside of a newer version of Unity if you're trying to compile it. On Windows, you should be able to run what I zipped immediately without anything.

**Comment by dfashbaugh** [comment]
Just verified that this runs for me on Mac just fine using Unity 2018.3.5f1.

**Comment by KacobJeith** [comment]
agh the unity build versioning will be the death of me... My mac is so small i had to delete all the unity builds. Is there a way to run this without unity installed?

**Pull request merged**
